[vehicleInfo]
vehicleType=10
vehicleNum=0
length=11.5
width=4.5
hight=5.5
box=0
v2x=1
[cloudInfo]
addr="42.159.123.217"
port=8883
[rtkudp]
ip="192.168.20.30"
port=18888
[rtkClient]
type=0
addr="203.107.45.154"
port=8002
user="qxmidt0093"
passwd="8a4d551"
mountPoint="RTCM32_GGB"
outUartPath="/dev/ttySAC1,/dev/ttySAC3"
outUartBaud="115200,115200"
rtkLinkTimeout=5
[rsu]
latitude=39.866315
longitude=110.050445
height=1424
type=1
serverAddr="192.168.20.20"
imei="864506031444863"
[record]
remoteAddr="192.168.20.50"
remotePort=8888
localPort=8888
[gnss]
type=2
outsideType=2
latitude=41.8016622
longitude=109.9861018
height=207.40
heading=0.0
[rabbitmq]
addr="116.213.168.196"
port=55672
username="guest"
passwd="guest"
[rcd]
type=0
vcuType=0
speedWarningValue=5
speedReductionValue=10
[icu]
reportObstacleTime=5
